### ISSUE TITLE
Switch for Centigrade or Farenheit conversion

### ISSUE THREAD

**Issue by svHatch** [sramsay/wu#29]
Include a switch that determines whether the reports are in degrees Celsius, or in degrees Farenheit. Pretty U.S. biased right now.

Thanks

**Comment by sramsay** [comment]
You're right, of course.  Been meaning to get to this for a long time.  

Should be easy to add.  I'll probably make it an option in the .condrc file, as well as a switch.

**Comment by sramsay** [comment]
Fixed in 3.10.0
