### ISSUE TITLE
Station ID

### ISSUE THREAD

**Issue by adnrcddly** [sramsay/wu#32]
I have created the .condrc file in my home directory and have my API in there, but I don't think it's recognizing the Weather Station ID. I am attaching the one I want to use. In place of "Lincoln, NE", can I place something from this station to pull its data?

![screen shot 2017-08-07 at 6 43 27 pm](https://user-images.githubusercontent.com/17524696/29051499-76df393e-7ba0-11e7-915f-72a5806230ac.png)

**Comment by sramsay** [comment]
Try using KSLC.
